# Generated by Django 4.2 on 2023-04-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
