# Generated by Django 4.2 on 2023-04-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.ImageField(upload_to=''),
        ),
    ]
